version: 4.29.0
markdownExploder: true
prd:
  prdFile: docs/template-development/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/template-development/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree/README.md
  - docs/testing/technical/testing-infrastructure-lessons-learned.md
  - docs/testing/technical/testing-patterns.md
  - docs/testing/technical/test-strategy-and-standards.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/template-development/stories
slashPrefix: BMad
